[target.armv7-unknown-linux-gnueabihf]
linker = "C:\\Program Files (x86)\\Arm GNU Toolchain arm-none-linux-gnueabihf\\13.3 rel1\\bin\\arm-none-linux-gnueabihf-gcc.exe"
#[target.aarch64-unknown-linux-gnu]
#linker = "C:\\Program Files (x86)\\Arm GNU Toolchain aarch64-none-linux-gnu\\13.3 rel1\\bin\\aarch64-none-linux-gnu-gcc.exe"
