[package]
name = "mlx90640-async"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-hal-async = "1.0.0"
heapless = "0.8.0"
libm = "0.2.13"

embassy-time = { version = "0.4.0", features = ["defmt", "defmt-timestamp-uptime"] }

defmt = "1.0.1"
defmt-rtt = "1.0.0"

[dev-dependencies]
embassy-executor = { version = "0.7.0", features = ["task-arena-size-98304", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt"] }
embassy-time = { version = "0.4.0", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-rp = { version = "0.4.0", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl", "rp235xa", "binary-info"] }

defmt = "1.0.1"
defmt-rtt = "1.0.0"

cortex-m-rt = "0.7.5"

panic-probe = { version = "1.0.0", features = ["print-defmt"] }
